package com.timesheet.enums;

public enum Positions {
	COP, DCOP, DRIVER_KOLWEZI, DRIVER_KASAJI, KPTA, SITE_SUPERVISOR_DILOLO, DAF, CLEANER_KOLWEZI, SIM,
	SSI, LOG_SUPPLY_CHAIN,LOG_ASSOCIATE, RECEPTIONIST, FINANCE_ASSOCIATE, FINANCE_OFFICER,GARDENER_KOLWEZI,
	GARDENER_KASAJI, CLEANER_KASAJI, HR, SITE_SUPERVISOR_KAPANGA, IT_OFFICER_COMM_FP, CONSULTANT, OTHER
	
}