package com.timesheet.enums;

public enum Positions {
	COP, DCOP, DRIVER, KPTA, SITE_SUPERVISOR_KASAJI, DAF, CLEANER_KOLWEZI, SIM,
	SSI, LOG_SUPPLY_CHAIN, RECEPTIONIST, FINANCE_ASSOCIATE, FINANCE_OFFICER,
	CLEANER_KASAJI, HR, SITE_SUPERVISOR_KAPANGA, IT_OFFICER_COMM_FP
	
}