package com.timesheet.enums;

public enum Positions {
	COP, DCOP, DRIVER, KPTA, SITE_SUPERVISOR_KASAJI, DAF, CLEANER_KOLWEZI, SIM, IT,
	SSI, LOG_SUPPLY_CHAIN, RECEPTIONIST, FINANCE_ASSOCIATE, FINANCE_ASSISTANT,
	CLEANER_KASAJI, HR, SITE_SUPERVISOR_KAPANGA
}
